name: ${project.name}
version: ${project.version}
author: Sait
main: me.sait.mobarena.extension.MobArenaExtension
api-version: 1.18
depend:
- MobArena
softdepend:
- MythicMobs
- DiscordSRV
commands:
  mobarenaextension:
    description: Base command for MobArenaExtension
    usage: |
      MobArenaExtension failed to load.
      There is an error in your server log with details.
    aliases: [max, maex]
