name: ${project.name}
version: ${project.version}
author: Sait
main: me.sait.mobarena.extension.MobArenaExtension
api-version: 1.18
depend:
- MobArena
softdepend:
- MythicMobs
- DiscordSRV
commands:
  mobarenaextension:
    description: Base command for MobArenaExtension
    usage: |
      /max reload
    aliases: [max, maex, mae]
