name: Test build

on:
  push:
    branches:
      - develop
      - release
  workflow_dispatch:
    branches:
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy artifact
      run: ls .
    - run: mkdir -v build
    - run: cd target
    - run: jar=".jar"
    - run: ls .
    - run: grep '.jar' | grep -v '^MobArenaExtension' | sed 's/\.[^.]*$//' | xargs -I '{}' cp -v '{}'"$jar" '../build/''{}-'"$GITHUB_SHA""$jar"
    - run: ls ../build
    - run: cd ..
    - name: Store artifact
      uses: actions/upload-artifact@v2
      with:
        name: snapshots
        path: build
